# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sto', '0003_auto_20170703_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='url',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
