# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sto', '0004_auto_20170703_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='master',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sto.Master'),
            preserve_default=False,
        ),
    ]
