# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sto', '0006_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='price',
            new_name='amount',
        ),
    ]
