# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sto', '0008_transaction_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='transaction_created',
            field=models.BooleanField(default=False),
        ),
    ]
