# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sto', '0010_auto_20170713_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
    ]
