# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sto', '0013_auto_20170715_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(default='2017-01-01'),
            preserve_default=False,
        ),
    ]
